on: [push]
 
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout Code

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Build RavenM
      run: dotnet build RavenM -c Release

    - name: Build Updater
      run: dotnet build RavenM.Updater -c Release

    - name: Upload RavenM
      uses: actions/upload-artifact@v3
      with:
        name: RavenM
        path: .\RavenM\bin\Release\net46\RavenM.dll
        if-no-files-found: error

    - name: Upload Updater
      uses: actions/upload-artifact@v3
      with:
        name: Updater
        path: .\RavenM.Updater\bin\Release\net461\RavenM.Updater.dll
        if-no-files-found: error
